---
- name: Deploy All
  hosts: localhost
  vars:
    Orgs:
      - {name: 'org1', pw: 'password1', nodeCount: 1, tls: false, dockerPortPrefix: 20, type: orderer }
      - {name: 'org2', pw: 'password2', nodeCount: 1, tls: false, dockerPortPrefix: 21, type: peer }
      - {name: 'org3', pw: 'password3', nodeCount: 1, tls: false, dockerPortPrefix: 22, type: peer }
    Chans:
      - {name: 'chan1'}
#      - {name: 'chan2'}
    Contracts:
      - {name: "fabcar", version: "1.0.0", location: "{{playbook_dir}}"}
#      - {name: "huycar", version: "5.0.0", location: "{{playbook_dir}}"}
    orgList: []
    chanList: []
    contractList: []
    gatewayList: []

  tasks:
    - name: Create Peer Orgs
      include_tasks: tasks/prep-peers.yaml
      with_items: "{{ Orgs }}"
      when: org['type'] == "peer"
      loop_control:
        loop_var: org
        index_var: count

    - name: Create Orderer Orgs
      include_tasks: tasks/prep-orderers.yaml
      with_items: "{{ Orgs }}"
      when: org['type'] == "orderer"
      loop_control:
        loop_var: org
        index_var: count

    - name: Create Channels
      include_tasks: tasks/prep-channels.yaml

    - name: Create Contracts
      include_tasks: tasks/prep-contracts.yaml

    - name: Create Gateways
      include_tasks: tasks/prep-gateways.yaml

    - debug: var=orgList
    - debug: var=chanList
    - debug: var=contractList
    - debug: var=gatewayList


    - include_role:
        name: ibm.blockchain_platform_manager
      vars:
        state: present
        infrastructure:
          type: docker
          docker:
            network: huy_network
        organizations: "{{orgList}}"
        channels: "{{chanList}}"
        contracts: "{{contractList}}"
        gateways: "{{gatewayList}}"