---
- name: Deploy All
  hosts: localhost
  vars:
    Orgs:
      - {name: 'org1', nodeCount: 1, tls: false, dockerPortPrefix: 20, type: orderer }
      - {name: 'org2', nodeCount: 2, tls: false, dockerPortPrefix: 21, type: peer }
      - {name: 'org3', nodeCount: 3, tls: false, dockerPortPrefix: 22, type: peer }
    Chans:
      - {name: 'chan1'}
      - {name: 'chan2'}
    Contracts:
      - {name: "fabcar", version: "1.0.0", location: "{{playbook_dir}}"}
      - {name: "org2cc", version: "1.0.0", location: "{{playbook_dir}}"}
      - {name: "huy2", version : "1.0.0", location: "{{playbook_dir}}"}
    orgList: []
    chanList: []
    contractList: []
    gatewayList: []
    debug: {}

  tasks:
    - name: Create Peer Orgs
      include_tasks: tasks/prep-peers.yaml
      with_items: "{{ Orgs }}"
      when: org['type'] == "peer"
      loop_control:
        loop_var: org
        index_var: count

    - name: Create Orderer Orgs
      include_tasks: tasks/prep-orderers.yaml
      with_items: "{{ Orgs }}"
      when: org['type'] == "orderer"
      loop_control:
        loop_var: org
        index_var: count

    - name: Create Channels
      include_tasks: tasks/prep-channels.yaml

    - name: Create Contracts
      include_tasks: tasks/prep-contracts.yaml

    - name: Create Gateways
      include_tasks: tasks/prep-gateways.yaml

    - name: Copy master config to file
      copy:
        content: "{{debug | combine({'orgList': orgList, 'chanList':chanList, 'contractList': contractList, 'gatewayList': gatewayList}) | to_nice_json }}"
        dest: "./debugFile.json"

    - include_role:
        name: ibm.blockchain_platform_manager
      vars:
        state: absent
        infrastructure:
          type: docker
          docker:
            network: my_network
        organizations: "{{orgList}}"
        channels: "{{chanList}}"
        contracts: "{{contractList}}"
        gateways: "{{gatewayList}}"