---
- name: Set facts
  set_fact:
    msp_id: "{{org.name}}MSP"
    ca_id: "{{org.name}}CA"
    admin: "{{org.name}}-admin"
    peers: []
    anchor_peers: []
    committing_peers: []
    endorsing_peers: []
    gateway_peers: []

- name: Get peer list
  include_tasks: build-peers.yaml
  with_sequence: start=1 end={{ org.nodeCount }}

- name: add items to array
  set_fact:
    orgList: "{{ orgList }} + [ {{ lookup('template', 'org.json.j2') | combine({'peers': peers}) | combine({'committing_peers': committing_peers, 'anchor_peers': anchor_peers, 'endorsing_peers': endorsing_peers  }) }} ]"
